services:
   db:
     image: ankane/pgvector
     container_name: pgvector
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dochat
     ports:
        - "5433:5432"

   redis:
     image: redis:7
     ports:
       - "6379:6379"


