"""vector 1024

Revision ID: b6059cc19a26
Revises: 6b275a83a19e
Create Date: 2026-08-24 20:25:24.407087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa
import pgvector 
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b6059cc19a26'
down_revision: Union[str, Sequence[str], None] = '6b275a83a19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('_typmod_cache')
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # op.drop_index(op.f('chunks_bm25_index'), table_name='chunks', postgresql_with={'key_field': 'id', 'text_fields': '{"content":{}}'}, postgresql_using='bm25')
    # op.drop_index(op.f('chunks_hnsw_index'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('chunks_hnsw_index'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # op.create_index(op.f('chunks_bm25_index'), 'chunks', ['id', 'content'], unique=False, postgresql_with={'key_field': 'id', 'text_fields': '{"content":{}}'}, postgresql_using='bm25')
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.create_table('_typmod_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('typmod', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_typmod_cache_pkey')),
    sa.UniqueConstraint('typmod', name=op.f('_typmod_cache_typmod_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
